export const SELECTED_USER = 'SELECTED_USER'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const USER_LOADED = 'USER_LOADED'
export const SELECTED_STORE = 'SELECTED_STORE'
export const SELECTED_CATEGORY = 'SELECTED_CATEGORY'
export const ITEM_ADDED = 'ITEM_ADDED'
export const ITEM_REMOVED = 'ITEM_REMOVED'
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY'
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY'
export const CLEAR_CART = 'CLEAR_CART'



